"""Curated metadata, keyed by song_key (derived from sequenceName).
This is the `songs` table: artist and year are properties of the song and are
true regardless of which show plays it. year=None means "needs review"."""

# Show definitions — display copy and the controlled category vocabulary, in
# the order the chips appear. Lives here rather than in a script because both
# build_catalog.py and init_db.py need it and two copies would drift; once a
# database exists the `shows` and `show_categories` tables are the source of
# truth and the admin page edits them, not this file.
#
# playlist_name is what the adapter asks FPP for. FPP stores playlists as JSON
# files in ~/media/playlists/ and refers to them by filename WITHOUT the .json,
# so 'NY_Dance_Party.json' on disk is 'NY_Dance_Party' here.
#
# Christmas and New Year's are the real names, from Paulin (2026-08-16).
# Halloween is still a placeholder — that playlist does not exist yet.
#
# Matching is tolerant of a .json suffix and of case, so either form works;
# see Follower.resolve_show. Confirm against a capture when convenient:
# tests/fixtures/captured/playlists_*.json is FPP's own list.
SHOW_DEFS = {
    "christmas": {
        "name": "Christmas 2025",
        "playlist_name": "All_Xmas_Songs - Alphabetic",
        "tagline": "The winner plays next.",
        "note": "",
        "theme": "christmas",
        # Instrumental sits with the other genre chips; Not-So-Christmasy is a
        # catch-all and stays last. Move it if you would rather it read
        # differently — sort_order is just this list's order.
        "categories": ["New this year", "Traditional", "Contemporary", "Spiritual",
                       "Crooners", "Rock & Roll", "Sing-Along", "Kids & Movies",
                       "Instrumental", "Not-So-Christmasy"],
    },
    "nye": {
        "name": "New Year's Eve 2026",
        "playlist_name": "NY_Dance_Party",
        "tagline": "The winner plays next.",
        "note": "Dec 29 – Jan 3",
        "theme": "nye",
        "categories": ["New this year", "Countdown", "Dance Tunes", "Pop", "Rock",
                       "Kids & Movies", "Throwback", "Instrumental"],
    },
    "halloween": {
        "name": "Halloween 2026",
        "playlist_name": "Halloween 2026",   # placeholder: no such playlist yet
        "tagline": "Catalog not built yet.",
        "note": "New show — playlist still to come",
        "theme": "halloween",
        "categories": [],
    },
}

META = {
 # key: (artist, year)
 "christmas-vacation":                              (None, None),
 "christmas-sarajevo-12-24-instrumental":           ("Trans-Siberian Orchestra", 1996),
 "let-it-snow-baby-its-cold-outside":               ("Alex G and Robby Word", None),
 "under-the-sea-the-little-mermaid":                ("Samuel E. Wright", 1989),
 "we-three-kings":                                  ("Alexander Jean", None),
 "frosty-the-snowman":                              ("Ben Rector", 2022),
 "frozen-let-it-go-sing-along-official-disney-hd":  ("Idina Menzel", 2013),
 "carol-of-the-bells":                              ("Monique Danielle", None),
 "feliz-navidad":                                   ("José Feliciano", 1970),
 "jingle-bell-rock":                                ("Bobby Helms", 1957),
 "silent-night-feat-reba-mcentire":                 ("Kelly Clarkson", 2021),
 "golden-kpop-demon-hunters":                       ("HUNTR/X", 2025),
 "do-you-hear-what-i-hear":                         ("Spiraling", None),
 "linus-and-lucy":                                  ("Vince Guaraldi Trio", 1964),
 "the-christmas-song-merry-christmas":              ('Nat "King" Cole', 1946),
 "frozen-2-into-the-unknown":                       ("Idina Menzel", 2019),
 "zero":                                            ("Imagine Dragons", 2018),
 "jingle-bells-epic-version":                       (None, None),
 "santa-wont-you-bring-me-love":                    (None, None),
 "first-snow-instrumental":                         ("Trans-Siberian Orchestra", 1996),
 "music-box-dancer-radio-version":                  ("DJ Schwede", None),
 "how-far-ill-go":                                  ("Auli'i Cravalho", 2016),
 "takin-care-of-christmas":                         ("Randy Bachman", None),
 "disney-medley-happily-ever-after":                ("Disney Medley", None),
 "believer":                                        ("Imagine Dragons", 2017),
 "anti-hero":                                       ("Taylor Swift", 2022),
 "mele-kalikimaka":                                 ("Bing Crosby", 1950),
 "300-violin-orchestra":                            (None, None),
 "little-drummer-boy-live":                         ("for KING & COUNTRY", None),
 "the-12-days-of-christmas":                        (None, None),
 "o-tannenbaum":                                    ("Mannheim Steamroller", 1984),
 "christmas-every-day":                             ("Simple Plan", None),
 "snoopys-christmas":                               ("The Royal Guardsmen", 1967),
 "oh-christmas-tree":                               ("Kids Now", None),
 "danger-zone-top-gun":                             ("Kenny Loggins", 1986),
 "what-a-wonderful-world-single":                   ("Louis Armstrong", 1967),
 "dance-the-night":                                 ("Dua Lipa", 2023),
 "sounding-joy":                                    ("Ellie Holcomb", None),
 "star-wars-funk-final":                            ("DJ Disco", None),
 "the-spirit-of-christmas-medley":                  ("Michael W. Smith & Friends", None),
 "my-favorite-things":                              ("Pentatonix", 2014),
 "carol-of-the-bells-foster-instrumental":          ("David Foster", 1993),
 "barbie-girl":                                     ("Aqua", 1997),
 "light-the-lights-edited":                         ("Lynne and Reg Dickson", None),
 "wizards-in-winter-instrumental":                  ("Trans-Siberian Orchestra", 2004),
 "its-the-most-wonderful-time-of-the-year":         ("Andy Williams", 1963),
 "taylor-swift-show":                               ("Taylor Swift", None),
 "hallelujah":                                      ("Pentatonix", 2016),
 "a-star-to-follow-short-short-xmas":               ("Trans-Siberian Orchestra", 2004),
 "here-comes-the-sun":                              ("The Beatles", 1969),
 "star-wars-imperial-march-x-carol-of-the-bells":   ("Samuel Kim Music", None),
 "queen-of-the-winter-night":                       ("Trans-Siberian Orchestra", 2004),
 "huron-carol-short-version":                       ("Heather Dale", None),
 "we-dont-talk-about-bruno":                        ("Lin-Manuel Miranda", 2021),
 "i-want-a-hippopotamus-for-christmas":             ("Gayla Peevey", 1953),
 "i-gotta-feeling":                                 ("Black Eyed Peas", 2009),
 "white-christmas-feat-ken-darby":                  ("Bing Crosby", 1942),
 "youre-a-mean-one-mr-grinch":                      ("Pentatonix", 2016),
 "dance-of-the-sugar-plum-fairy":                   ("Michael Maxwell", None),
 "cant-stop-the-feeling-film-final":                ("Justin Timberlake", 2016),
 "i-heard-the-bells-on-christmas-day":              ("Casting Crowns", 2008),
 "light-of-christmas-feat-tobymac":                 ("Owl City", 2012),
 "life-is-a-highway":                               ("Rascal Flatts", 2006),
 "trim-up-the-tree":                                ("MGM Studio Chorus & Orchestra", 1966),
 "nutcracker-trepak-russian-dance":                 ("Tchaikovsky", 1892),
 # NYE-only
 "darude-sandstorm":                                ("Darude", 1999),
 "the-movie-medley":                                ("Straight No Chaser", None),
 "toccata-and-fugue-paranormal-remix":              ("J.S. Bach, remixed", None),
 "dont-start-now":                                  ("Dua Lipa", 2019),
 "shut-up-and-dance":                               ("Walk the Moon", 2014),
 "auld-lang-syne":                                  (None, None),
}

CHRISTMAS_CATS = {
 "christmas-vacation":                             ["Sing-Along","Not-So-Christmasy"],
 "christmas-sarajevo-12-24-instrumental":          ["Rock & Roll","Traditional","Instrumental"],
 "let-it-snow-baby-its-cold-outside":              ["Contemporary"],
 "under-the-sea-the-little-mermaid":               ["Kids & Movies","Not-So-Christmasy"],
 "we-three-kings":                                 ["Traditional","Spiritual"],
 "frosty-the-snowman":                             ["Crooners","Contemporary","Kids & Movies"],
 "frozen-let-it-go-sing-along-official-disney-hd": ["Kids & Movies","Sing-Along","Not-So-Christmasy"],
 "carol-of-the-bells":                             ["Traditional"],
 "feliz-navidad":                                  ["Contemporary","Sing-Along"],
 "jingle-bell-rock":                               ["Rock & Roll","Sing-Along"],
 "silent-night-feat-reba-mcentire":                ["Spiritual","Contemporary"],
 "golden-kpop-demon-hunters":                      ["New this year","Kids & Movies","Not-So-Christmasy"],
 "do-you-hear-what-i-hear":                        ["Rock & Roll","Spiritual"],
 "linus-and-lucy":                                 ["Kids & Movies"],
 "the-christmas-song-merry-christmas":             ["Crooners","Traditional"],
 "frozen-2-into-the-unknown":                      ["Kids & Movies","Not-So-Christmasy"],
 "zero":                                           ["Rock & Roll","Not-So-Christmasy"],
 "jingle-bells-epic-version":                      ["Traditional","Rock & Roll"],
 "santa-wont-you-bring-me-love":                   ["New this year","Contemporary"],
 "first-snow-instrumental":                        ["Rock & Roll","Contemporary","Instrumental"],
 "music-box-dancer-radio-version":                 ["Contemporary","Instrumental"],
 "how-far-ill-go":                                 ["Kids & Movies","Not-So-Christmasy"],
 "takin-care-of-christmas":                        ["Rock & Roll"],
 "disney-medley-happily-ever-after":               ["Kids & Movies"],
 "believer":                                       ["Not-So-Christmasy","Rock & Roll"],
 "anti-hero":                                      ["Not-So-Christmasy"],
 "mele-kalikimaka":                                ["Crooners"],
 "300-violin-orchestra":                           ["New this year","Contemporary","Instrumental"],
 "little-drummer-boy-live":                        ["Rock & Roll","Spiritual"],
 "the-12-days-of-christmas":                       ["Contemporary","Sing-Along"],
 "o-tannenbaum":                                   ["Traditional","Contemporary"],
 "christmas-every-day":                            ["Contemporary","Rock & Roll"],
 "snoopys-christmas":                              ["New this year","Rock & Roll","Sing-Along"],
 "oh-christmas-tree":                              ["Sing-Along","Kids & Movies","Traditional"],
 "danger-zone-top-gun":                            ["Not-So-Christmasy","Rock & Roll"],
 "what-a-wonderful-world-single":                  ["Crooners","Not-So-Christmasy"],
 "dance-the-night":                                ["Not-So-Christmasy"],
 "sounding-joy":                                   ["Spiritual","Contemporary"],
 "star-wars-funk-final":                           ["Kids & Movies","Not-So-Christmasy"],
 "the-spirit-of-christmas-medley":                 ["Contemporary","Spiritual"],
 "my-favorite-things":                             ["Kids & Movies","Contemporary"],
 "carol-of-the-bells-foster-instrumental":         ["Contemporary","Traditional","Instrumental"],
 "barbie-girl":                                    ["Kids & Movies","Not-So-Christmasy"],
 "light-the-lights-edited":                        ["Contemporary"],
 "wizards-in-winter-instrumental":                 ["Rock & Roll","Contemporary","Instrumental"],
 "its-the-most-wonderful-time-of-the-year":        ["Crooners","Sing-Along"],
 "taylor-swift-show":                              ["Not-So-Christmasy"],
 "hallelujah":                                     ["Contemporary","Spiritual"],
 "a-star-to-follow-short-short-xmas":              ["Traditional","Rock & Roll"],
 "here-comes-the-sun":                             ["Not-So-Christmasy","Rock & Roll"],
 "star-wars-imperial-march-x-carol-of-the-bells":  ["Contemporary","Traditional","Kids & Movies"],
 "queen-of-the-winter-night":                      ["Rock & Roll"],
 "huron-carol-short-version":                      ["Spiritual","Traditional"],
 "we-dont-talk-about-bruno":                       ["Kids & Movies","Not-So-Christmasy"],
 "i-want-a-hippopotamus-for-christmas":            ["Sing-Along","Kids & Movies"],
 "i-gotta-feeling":                                ["Not-So-Christmasy"],
 "white-christmas-feat-ken-darby":                 ["Crooners","Traditional"],
 "youre-a-mean-one-mr-grinch":                     ["Sing-Along","Kids & Movies"],
 "dance-of-the-sugar-plum-fairy":                  ["Traditional","Contemporary"],
 "cant-stop-the-feeling-film-final":               ["Not-So-Christmasy","Kids & Movies"],
 "i-heard-the-bells-on-christmas-day":             ["Spiritual","Contemporary"],
 "light-of-christmas-feat-tobymac":                ["Spiritual","Contemporary"],
 "life-is-a-highway":                              ["Kids & Movies","Not-So-Christmasy"],
 "trim-up-the-tree":                               ["Kids & Movies","Sing-Along"],
 "nutcracker-trepak-russian-dance":                ["Traditional"],
}

NYE_CATS = {
 "darude-sandstorm":                               ["Dance Tunes","Instrumental"],
 "the-movie-medley":                               ["Kids & Movies","Pop"],
 "cant-stop-the-feeling-film-final":               ["Pop","Dance Tunes","Kids & Movies","Countdown"],
 "under-the-sea-the-little-mermaid":               ["Kids & Movies"],
 "here-comes-the-sun":                             ["Throwback","Rock"],
 "disney-medley-happily-ever-after":               ["Kids & Movies"],
 "star-wars-funk-final":                           ["Kids & Movies","Dance Tunes"],
 "barbie-girl":                                    ["Pop","Throwback","Dance Tunes"],
 "toccata-and-fugue-paranormal-remix":             ["Dance Tunes","Instrumental"],
 "frozen-let-it-go-sing-along-official-disney-hd": ["Kids & Movies"],
 "anti-hero":                                      ["Pop","Dance Tunes"],
 "what-a-wonderful-world-single":                  ["Throwback"],
 "dont-start-now":                                 ["New this year","Pop","Dance Tunes"],
 "music-box-dancer-radio-version":                 ["Dance Tunes","Instrumental"],
 "taylor-swift-show":                              ["Pop"],
 "life-is-a-highway":                              ["Kids & Movies","Rock"],
 "shut-up-and-dance":                              ["Rock","Dance Tunes","Pop"],
 "golden-kpop-demon-hunters":                      ["New this year","Pop","Kids & Movies"],
 "first-snow-instrumental":                        ["Instrumental","Rock"],
 "how-far-ill-go":                                 ["Kids & Movies"],
 "danger-zone-top-gun":                            ["Throwback","Rock"],
 "zero":                                           ["Rock","Pop"],
 "we-dont-talk-about-bruno":                       ["Kids & Movies","Pop"],
 "believer":                                       ["Rock","Pop"],
 "i-gotta-feeling":                                ["Dance Tunes","Pop","Countdown"],
 "auld-lang-syne":                                 ["Countdown"],
}

# What the earlier hand-typed song list contained that the real playlists do not
PREVIOUSLY_LISTED_NOT_IN_PLAYLIST = {
 "christmas": ["Hallelujah Chorus (Ambrosian Singers)",
               "Ice Storm (Lindsey Stirling)",
               "Twelve Days of Christmas (Bob & Doug McKenzie)"],
 "nye":       ["Dance the Night (Dua Lipa)"],
}
